### ISSUE TITLE
Health Check Service Port

### ISSUE THREAD

**Issue by HarshadRanganathan** [HarshadRanganathan/spring-boot-example#2]
Expose health check in a different service port - this is to have it in a private mode (LB health check) so that it's not exposed along with the public endpoint.

e.g. 

```yaml
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: actuator
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
```
